### ISSUE TITLE
How to use the SOAP Endpoint

### ISSUE THREAD

**Issue by elspiko** [nmaier/simpleDLNA#10]
This is less of an 'issue' more a question, but I'm having trouble deciphering how to use the SOAP endpoint.

What I'd like is to be able to make a request to get a list of videos with their streaming endpoint, is this currently possible, if so, how?

Many thanks

**Comment by nmaier** [comment]
See the DLNA/UPnP specs please. You can also use something like http://opentools.homeip.net/dev-tools-for-upnp to poke the service.
