### ISSUE TITLE
Opening source in MS Visual Studio Community 2017 

### ISSUE THREAD

**Issue by BrainforgeUK** [nmaier/simpleDLNA#38]
Downloaded SDLNA source.
Opened project sdlna.sln
Got errors about ...\setup\setup.vdproj

See attached messages:
[vs17 messages.zip](https://github.com/nmaier/simpleDLNA/files/1057711/vs17.messages.zip)

**Comment by PFloeschel** [comment]
You need to add the [Microsoft Visual Studio 2017 Installer Projects](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.MicrosoftVisualStudio2017InstallerProjects) extension to your VS Community.
